In [22]:
import pandas as pd
pd.set_option('display.max_columns', None)

viable_proposals = pd.read_csv("viable_proposals.csv")

In [19]:
# df.drop_duplicates(subset=["total_duration", ""])

In [25]:
smpl_onetwotrip = viable_proposals[(viable_proposals.idx_new == 0) & (viable_proposals.partner_id == "20")].sort_values("price").head(1)
smpl_onetwotrip

Empty DataFrame
Columns: [segment, total_duration, stops_airports, max_stops, max_stop_duration, carriers, segment_durations, segments_time, segments_airports, segments_rating, tags, is_mixed, partner_id, idx, currency, price, url, flights_baggage, flights_handbags, flight_additional_tariff_infos, viable_handbags, viable_baggage, has_handbags, has_baggage, flight_to, flight_back, tariff_to, tariff_back, rounded_price_5k, has_exchange, has_return, airlines_list_to, airlines_list_back, flight_to_time_raw, flight_back_time_raw, flight_to_time, flight_back_time, idx_new, has_blacklisted_airlines, has_preferred_airlines]
Index: []

In [23]:
viable_proposals[viable_proposals.partner_id == 20]

,segment,total_duration,stops_airports,max_stops,max_stop_duration,carriers,segment_durations,segments_time,segments_airports,segments_rating,tags,is_mixed,partner_id,idx,currency,price,url,flights_baggage,flights_handbags,flight_additional_tariff_infos,viable_handbags,viable_baggage,has_handbags,has_baggage,flight_to,flight_back,tariff_to,tariff_back,rounded_price_5k,has_exchange,has_return,airlines_list_to,airlines_list_back,flight_to_time_raw,flight_back_time_raw,flight_to_time,flight_back_time,idx_new,has_blacklisted_airlines,has_preferred_airlines
201,[{'flight': [{'aircraft': 'Airbus A321-100/200...,535,"['SAW', 'FCO']",1,135,['PC'],"(535,)","[[1750992900, 1751021400]]","[['LED', 'FCO']]",7.679,['convenient_ticket'],NaN,20,878,rub,47821,2000002,"[['1PC20', '1PC20']]","[['1PC3x30x15x40', '1PC3x30x15x40']]","[[{}, {}]]",1PC3x30x15x40,1PC20,True,True,{'flight': [{'aircraft': 'Airbus A321-100/200'...,{},"[{}, {}]",NaN,50000,False,False,"('PC', 'PC')",(),02:55,0,2,0,0,False,True
202,[{'flight': [{'aircraft': 'Airbus A321-100/200...,710,"['SAW', 'FCO']",1,310,['PC'],"(710,)","[[1750992900, 1751031900]]","[['LED', 'FCO']]",6.574,"['convenient_ticket', 'long_layover']",NaN,20,879,rub,47821,2000001,"[['1PC20', '1PC20']]","[['1PC3x30x15x40', '1PC3x30x15x40']]","[[{}, {}]]",1PC3x30x15x40,1PC20,True,True,{'flight': [{'aircraft': 'Airbus A321-100/200'...,{},"[{}, {}]",NaN,50000,False,False,"('PC', 'PC')",(),02:55,0,2,0,11,False,True
203,[{'flight': [{'aircraft': 'Airbus A321-100/200...,1975,"['SAW', 'FCO']",1,1575,['PC'],"(1975,)","[[1750992900, 1751107800]]","[['LED', 'FCO']]",5.315,"['long_layover', 'overnight_layover', 'night_t...",NaN,20,880,rub,71551,2000047,"[['1PC20', '1PC']]","[['1PC3x30x15x40', '1PC']]","[[{}, {}]]",1PC3x30x15x40,1PC20,True,True,{'flight': [{'aircraft': 'Airbus A321-100/200'...,{},"[{}, {}]",NaN,70000,False,False,"('PC', 'PC')",(),02:55,0,2,0,441,False,True
204,[{'flight': [{'aircraft': 'Airbus A321-100/200...,1975,"['SAW', 'FCO']",1,1575,['PC'],"(1975,)","[[1750992900, 1751107800]]","[['LED', 'FCO']]",5.315,"['long_layover', 'overnight_layover', 'night_t...",NaN,20,880,rub,51916,2000003,"[['1PC20', '1PC20']]","[['1PC3x30x15x40', '1PC3x30x15x40']]","[[{}, {}]]",1PC3x30x15x40,1PC20,True,True,{'flight': [{'aircraft': 'Airbus A321-100/200'...,{},"[{}, {}]",NaN,50000,False,False,"('PC', 'PC')",(),02:55,0,2,0,441,False,True
205,"[{'flight': [{'aircraft': 'Airbus A330-200', '...",3405,"['IST', 'FCO']",1,3010,['TK'],"(3405,)","[[1750988100, 1751188800]]","[['LED', 'FCO']]",4.457,"['has_night_transfer', 'night_transfer', 'long...",NaN,20,881,rub,53241,2000004,"[['1PC30', '1PC30']]","[['1PC8x40x23x55', '1PC8x40x23x55']]","[[{}, {}]]",1PC8x40x23x55,1PC30,True,True,"{'flight': [{'aircraft': 'Airbus A330-200', 'a...",{},"[{}, {}]",NaN,50000,False,False,"('TK', 'TK')",(),01:35,0,1,0,1056,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,[{'flight': [{'aircraft': 'Airbus A321 (sharkl...,3040,"['IST', 'FCO']",1,2630,['TK'],"(3040,)","[[1751028600, 1751207400]]","[['LED', 'FCO']]",4.676,"['overnight_layover', 'has_night_transfer', 'n...",NaN,20,927,rub,111759,2000061,"[['1PC30', '1PC30']]","[['1PC8x40x23x55', '1PC8x40x23x55']]","[[{}, {}]]",1PC8x40x23x55,1PC30,True,True,{'flight': [{'aircraft': 'Airbus A321 (sharkle...,{},"[{}, {}]",NaN,110000,False,False,"('TK', 'TK')",(),12:50,0,12,0,958,False,True
259,[{'flight': [{'aircraft': 'Airbus A321 (sharkl...,4905,"['IST', 'FCO']",1,4500,['TK'],"(4905,)","[[1751003100, 1751293800]]","[['LED', 'FCO']]",3.057,"['overnight_layover', 'has_night_transfer', 'n...",NaN,20,928,rub,111759,2000058,"[['1PC30', '1PC30']]","[['1PC8x40x23x55', '1PC8x40x23x55']]","[[{}, {}]]",1PC8x40x23x55,1PC30,True,True,{'flight': [{'aircraft': 'Airbus A321 (sharkle...,{},"[{}, {}]",NaN,110000,False,False,"('TK', 'TK')",(),05:45,0,5,0,1132,False,True
260,"[{'flight': [{'aircraft': 'Airbus A330-200', '...",2275,"['IST', 'FCO']",1,1880,['TK'],"(2275,)","[[1750988100, 1751121000]]","[['LED', 'FCO']]",5.135,"['overnight_layover', 'night_transfer', 'has_n...",NaN,20,929,rub,111759,2000062,"[['1PC30', '1PC30']]","[['1PC8x40x23x55', '1PC8x40x23x55']]","[[{}, {}]]",1PC8x40x23x55,1PC30,True,True,"{'flight': [{'aircraft': 'Airbus A330-200', 'a...",{},"[{}, {}]",NaN,110000,False,False,"('TK', 'TK')",(),01:35,0,1,0,578,False,True
261,"[{'flight': [{'aircraft': 'Airbus A330-200', '...",4870,"['IST', 'FCO']",1,4480,['TK'],"(4870,)","[[1750988100, 1751276700]]","[['LED', 'FCO']]",3.578,"['overnight_layover', 'has_night_transfer', 'n...",NaN,20,930,rub,146850,2000064,"[['1PC30', '1PC30']]","[['1PC8x40x23x55', '1PC8x40x23x55']]","[[{}, {}]]",1PC8x40x23x55,1PC30,True,True,"{'flight': [{'aircraft': 'Airbus A330-200', 'a...",{},"[{}, {}]",NaN,150000,False,False,"('TK', 'TK')",(),01:35,0,1,0,1131,False,True
262,[{'flight': [{'aircraft': 'Airbus A321 (sharkl...,4195,"['IST', 'FCO']",1,3790,['TK'],"(4195,)","[[1751028600, 1751276700]]","[['LED', 'FCO']]",3.983,"['long_layover', 'overnight_layover', 'night_t...",NaN,20,931,rub,146850,2000065,"[['1PC30', '1PC30']]","[['1PC8x40x23x55', '1PC8x40x23x55']]","[[{}, {}]]",1PC8x40x23x55,1PC30,True,True,{'flight': [{'aircraft': 'Airbus A321 (sharkle...,{},"[{}, {}]",NaN,150000,False,False,"('TK', 'TK')",(),12:50,0,12,0,1129,False,True

In [14]:
viable_proposals.sort_values(["has_exchange", "has_return", "has_handbags", "has_baggage"], ascending=False, inplace=True)
viable_proposals.drop_duplicates(subset=["idx_new", "price"], inplace=True)

In [15]:
viable_proposals[viable_proposals.price == 77776] # 356 to del

,segment,total_duration,stops_airports,max_stops,max_stop_duration,carriers,segment_durations,segments_time,segments_airports,segments_rating,tags,is_mixed,idx,currency,price,url,flights_baggage,flights_handbags,flight_additional_tariff_infos,viable_handbags,viable_baggage,has_handbags,has_baggage,flight_to,flight_back,tariff_to,tariff_back,rounded_price_5k,has_exchange,has_return,airlines_list_to,airlines_list_back,flight_to_time_raw,flight_back_time_raw,flight_to_time,flight_back_time,idx_new,has_blacklisted_airlines,has_preferred_airlines
357,"[{'flight': [{'aircraft': 'Airbus A330-200', '...",550,"['IST', 'FCO']",1,160,['TK'],"(550,)","[[1750988100, 1751017500]]","[['LED', 'FCO']]",7.17,['convenient_ticket'],NaN,387,rub,77776,18300356,"[['1PC30', '1PC30']]","[['1PC8x40x23x55', '1PC8x40x23x55']]",[[{'return_before_flight': {'available': True}...,1PC8x40x23x55,1PC30,True,True,"{'flight': [{'aircraft': 'Airbus A330-200', 'a...",{},"[{'return_before_flight': {'available': True},...",NaN,80000,True,True,"('TK', 'TK')",(),01:35,0,1,0,1,False,True
356,"[{'flight': [{'aircraft': 'Airbus A330-200', '...",550,"['IST', 'FCO']",1,160,['TK'],"(550,)","[[1750988100, 1751017500]]","[['LED', 'FCO']]",7.17,['convenient_ticket'],NaN,387,rub,77776,18300355,"[['1PC30', '1PC30']]","[['1PC8x40x23x55', '1PC8x40x23x55']]",[[{'return_before_flight': {'available': False...,1PC8x40x23x55,1PC30,True,True,"{'flight': [{'aircraft': 'Airbus A330-200', 'a...",{},[{'return_before_flight': {'available': False}...,NaN,80000,False,False,"('TK', 'TK')",(),01:35,0,1,0,1,False,True

In [16]:
print(viable_proposals.shape)

viable_proposals.drop_duplicates(subset=["idx_new", "price"], inplace=True)
print(viable_proposals.shape)

(944, 39)
(875, 39)

In [17]:
viable_proposals[viable_proposals.price == 77776]

,segment,total_duration,stops_airports,max_stops,max_stop_duration,carriers,segment_durations,segments_time,segments_airports,segments_rating,tags,is_mixed,idx,currency,price,url,flights_baggage,flights_handbags,flight_additional_tariff_infos,viable_handbags,viable_baggage,has_handbags,has_baggage,flight_to,flight_back,tariff_to,tariff_back,rounded_price_5k,has_exchange,has_return,airlines_list_to,airlines_list_back,flight_to_time_raw,flight_back_time_raw,flight_to_time,flight_back_time,idx_new,has_blacklisted_airlines,has_preferred_airlines
357,"[{'flight': [{'aircraft': 'Airbus A330-200', '...",550,"['IST', 'FCO']",1,160,['TK'],"(550,)","[[1750988100, 1751017500]]","[['LED', 'FCO']]",7.17,['convenient_ticket'],NaN,387,rub,77776,18300356,"[['1PC30', '1PC30']]","[['1PC8x40x23x55', '1PC8x40x23x55']]",[[{'return_before_flight': {'available': True}...,1PC8x40x23x55,1PC30,True,True,"{'flight': [{'aircraft': 'Airbus A330-200', 'a...",{},"[{'return_before_flight': {'available': True},...",NaN,80000,True,True,"('TK', 'TK')",(),01:35,0,1,0,1,False,True

In [4]:
indices_already_displayed = []

smallest_durations_by_group = viable_proposals.groupby("idx_new")[
    "total_duration"
].min()
smallest_durations = smallest_durations_by_group.nsmallest(2).values
min_price_indices = (
    viable_proposals[
        viable_proposals.total_duration.isin(smallest_durations)
    ]
    .groupby("idx_new")["price"]
    .idxmin()
)
fastest_optimal = viable_proposals.loc[min_price_indices]

In [5]:
fastest_optimal

,segment,total_duration,stops_airports,max_stops,max_stop_duration,carriers,segment_durations,segments_time,segments_airports,segments_rating,tags,is_mixed,idx,currency,price,url,flights_baggage,flights_handbags,flight_additional_tariff_infos,viable_handbags,viable_baggage,has_handbags,has_baggage,flight_to,flight_back,tariff_to,tariff_back,rounded_price_5k,has_exchange,has_return,airlines_list_to,airlines_list_back,flight_to_time_raw,flight_back_time_raw,flight_to_time,flight_back_time,idx_new,has_blacklisted_airlines,has_preferred_airlines
31,[{'flight': [{'aircraft': 'Airbus A321-100/200...,535,"['SAW', 'FCO']",1,135,['PC'],"(535,)","[[1750992900, 1751021400]]","[['LED', 'FCO']]",7.679,['convenient_ticket'],NaN,28,rub,43970,7000001,"[['1PC20', '1PC20']]","[['1PC3x30x15x40', '1PC3x30x15x40']]",[[{'return_before_flight': {'available': False...,1PC3x30x15x40,1PC20,True,True,{'flight': [{'aircraft': 'Airbus A321-100/200'...,{},[{'return_before_flight': {'available': False}...,NaN,40000,False,False,"('PC', 'PC')",(),02:55,0,2,0,0,False,True
405,"[{'flight': [{'aircraft': 'Airbus A330-200', '...",550,"['IST', 'FCO']",1,160,['TK'],"(550,)","[[1750988100, 1751017500]]","[['LED', 'FCO']]",7.170,['convenient_ticket'],NaN,422,rub,77776,18300359,"[['1PC30', '1PC30']]","[['1PC8x40x23x55', '1PC8x40x23x55']]",[[{'return_before_flight': {'available': True}...,1PC8x40x23x55,1PC30,True,True,"{'flight': [{'aircraft': 'Airbus A330-200', 'a...",{},"[{'return_before_flight': {'available': True},...",NaN,80000,True,True,"('TK', 'TK')",(),01:35,0,1,0,1,False,True

In [3]:
df["idx_new"] = df.groupby(
    [
        "total_duration",
        "max_stops",
        "max_stop_duration",
        "segment_durations",
        "airlines_list_to",
        "airlines_list_back",
        "flight_to_time_raw",
        "flight_back_time_raw",
    ]
).ngroup()

In [6]:
df    [[
        "total_duration",
        "max_stops",
        "max_stop_duration",
        "segment_durations",
        "airlines_list_to",
        "airlines_list_back",
        "flight_to_time_raw",
        "flight_back_time_raw",
    ]]

,total_duration,max_stops,max_stop_duration,segment_durations,airlines_list_to,airlines_list_back,flight_to_time_raw,flight_back_time_raw
0,1600,1,1190,[1600],"('TK', 'TK')",(),12:50,0
1,1290,1,880,[1290],"('TK', 'TK')",(),12:50,0
2,835,1,440,[835],"('TK', 'TK')",(),01:35,0
3,1125,1,725,[1125],"('TK', 'TK')",(),05:45,0
4,1375,1,985,[1375],"('TK', 'TK')",(),01:35,0
...,...,...,...,...,...,...,...,...
1539,2090,2,1080,[2090],"('UT', 'QR', 'QR')",(),21:35,0
1540,1965,1,1570,[1965],"('TK', 'TK')",(),01:35,0
1541,1965,1,1570,[1965],"('TK', 'TK')",(),01:35,0
1542,2275,1,1880,[2275],"('TK', 'TK')",(),01:35,0
1543,2025,1,1620,[2025],"('TK', 'TK')",(),05:45,0

In [7]:
tuple([1,2,3,4,1])

(1, 2, 3, 4, 1)

In [4]:
smallest_durations_by_group = df.groupby("idx_new")["total_duration"].min()
df_smallest_duration = smallest_durations_by_group.nsmallest(2).values

df_smallest_duration

array([535, 550])

In [ ]:
min_price_indices = df[df.total_duration.isin(df_smallest_duration)].groupby("idx_new")["price"].idxmin()
df_min_price_by_group = df.loc[min_price_indices]

df_min_price_by_group

,segment,total_duration,stops_airports,max_stops,max_stop_duration,carriers,segment_durations,segments_time,segments_airports,segments_rating,tags,is_mixed,idx,currency,price,url,flights_baggage,flights_handbags,flight_additional_tariff_infos,viable_handbags,viable_baggage,has_handbags,has_baggage,flight_to,flight_back,tariff_to,tariff_back,rounded_price_5k,has_exchange,has_return,airlines_list_to,airlines_list_back,flight_to_time_raw,flight_back_time_raw,flight_to_time,flight_back_time,has_blacklisted_airlines,has_preferred_airlines,idx_new
50,[{'flight': [{'aircraft': 'Airbus A321-100/200...,535,"['SAW', 'FCO']",1,135,['PC'],[535],"[[1750992900, 1751021400]]","[['LED', 'FCO']]",7.679,['convenient_ticket'],NaN,49,rub,43970,7000001,"[['1PC20', '1PC20']]","[['1PC3x30x15x40', '1PC3x30x15x40']]",[[{'return_before_flight': {'available': False...,1PC3x30x15x40,1PC20,True,True,{'flight': [{'aircraft': 'Airbus A321-100/200'...,{},[{'return_before_flight': {'available': False}...,NaN,40000,False,False,"['PC', 'PC']",[],02:55,0,2,0,False,True,0
891,"[{'flight': [{'aircraft': 'Airbus A330-200', '...",550,"['IST', 'FCO']",1,160,['TK'],[550],"[[1750988100, 1751017500]]","[['LED', 'FCO']]",7.170,['convenient_ticket'],NaN,855,rub,77776,18300535,"[['1PC30', '1PC30']]","[['1PC8x40x23x55', '1PC8x40x23x55']]",[[{'return_before_flight': {'available': True}...,1PC8x40x23x55,1PC30,True,True,"{'flight': [{'aircraft': 'Airbus A330-200', 'a...",{},"[{'return_before_flight': {'available': True},...",NaN,80000,True,True,"['TK', 'TK']",[],01:35,0,1,0,False,True,1

In [10]:
df["total_duration"].nsmallest(10).unique()

array([535])

In [6]:
df[df.idx == 802]

,segment,total_duration,stops_airports,max_stops,max_stop_duration,carriers,segment_durations,segments_time,segments_airports,segments_rating,tags,is_mixed,idx,currency,price,url,flights_baggage,flights_handbags,flight_additional_tariff_infos,viable_handbags,viable_baggage,has_handbags,has_baggage,flight_to,flight_back,tariff_to,tariff_back,rounded_price_5k,has_exchange,has_return,airlines_list_to,airlines_list_back,flight_to_time_raw,flight_back_time_raw,flight_to_time,flight_back_time,has_blacklisted_airlines,has_preferred_airlines,idx_new
811,[{'flight': [{'aircraft': 'Airbus A321 (sharkl...,1125,"['IST', 'FCO']",1,725,['TK'],[1125],"[[1751003100, 1751067000]]","[['LED', 'FCO']]",5.575,"['convenient_ticket', 'long_layover']",NaN,802,rub,60572,18300415,"[['1PC23', '1PC23']]","[['1PC8x40x23x55', '1PC8x40x23x55']]",[[{'return_before_flight': {'available': False...,1PC8x40x23x55,1PC23,True,True,{'flight': [{'aircraft': 'Airbus A321 (sharkle...,{},[{'return_before_flight': {'available': False}...,NaN,60000,False,False,"['TK', 'TK']",[],05:45,0,5,0,False,True,103
812,[{'flight': [{'aircraft': 'Airbus A321 (sharkl...,1125,"['IST', 'FCO']",1,725,['TK'],[1125],"[[1751003100, 1751067000]]","[['LED', 'FCO']]",5.575,"['convenient_ticket', 'long_layover']",NaN,802,rub,60572,18300416,"[['1PC23', '1PC23']]","[['1PC8x40x23x55', '1PC8x40x23x55']]",[[{'return_before_flight': {'available': False...,1PC8x40x23x55,1PC23,True,True,{'flight': [{'aircraft': 'Airbus A321 (sharkle...,{},[{'return_before_flight': {'available': False}...,NaN,60000,True,False,"['TK', 'TK']",[],05:45,0,5,0,False,True,103
813,[{'flight': [{'aircraft': 'Airbus A321 (sharkl...,1125,"['IST', 'FCO']",1,725,['TK'],[1125],"[[1751003100, 1751067000]]","[['LED', 'FCO']]",5.575,"['convenient_ticket', 'long_layover']",NaN,802,rub,63767,18300475,"[['1PC30', '1PC30']]","[['1PC8x40x23x55', '1PC8x40x23x55']]",[[{'return_before_flight': {'available': False...,1PC8x40x23x55,1PC30,True,True,{'flight': [{'aircraft': 'Airbus A321 (sharkle...,{},[{'return_before_flight': {'available': False}...,NaN,60000,False,False,"['TK', 'TK']",[],05:45,0,5,0,False,True,103
814,[{'flight': [{'aircraft': 'Airbus A321 (sharkl...,1125,"['IST', 'FCO']",1,725,['TK'],[1125],"[[1751003100, 1751067000]]","[['LED', 'FCO']]",5.575,"['convenient_ticket', 'long_layover']",NaN,802,rub,63767,18300476,"[['1PC30', '1PC30']]","[['1PC8x40x23x55', '1PC8x40x23x55']]",[[{'return_before_flight': {'available': True}...,1PC8x40x23x55,1PC30,True,True,{'flight': [{'aircraft': 'Airbus A321 (sharkle...,{},"[{'return_before_flight': {'available': True},...",NaN,60000,True,True,"['TK', 'TK']",[],05:45,0,5,0,False,True,103
815,[{'flight': [{'aircraft': 'Airbus A321 (sharkl...,1125,"['IST', 'FCO']",1,725,['TK'],[1125],"[[1751003100, 1751067000]]","[['LED', 'FCO']]",5.575,"['convenient_ticket', 'long_layover']",NaN,802,rub,108718,18300477,"[['1PC30', '1PC30']]","[['1PC8x40x23x55', '1PC8x40x23x55']]",[[{'return_before_flight': {'available': False...,1PC8x40x23x55,1PC30,True,True,{'flight': [{'aircraft': 'Airbus A321 (sharkle...,{},[{'return_before_flight': {'available': False}...,NaN,110000,False,False,"['TK', 'TK']",[],05:45,0,5,0,False,True,103
816,[{'flight': [{'aircraft': 'Airbus A321 (sharkl...,1125,"['IST', 'FCO']",1,725,['TK'],[1125],"[[1751003100, 1751067000]]","[['LED', 'FCO']]",5.575,"['convenient_ticket', 'long_layover']",NaN,802,rub,108718,18300478,"[['1PC30', '1PC30']]","[['1PC8x40x23x55', '1PC8x40x23x55']]","[[{'return_before_flight': {'available': True,...",1PC8x40x23x55,1PC30,True,True,{'flight': [{'aircraft': 'Airbus A321 (sharkle...,{},"[{'return_before_flight': {'available': True, ...",NaN,110000,True,True,"['TK', 'TK']",[],05:45,0,5,0,False,True,103

In [4]:
df.idx.value_counts()

idx
802     6
803     6
824     6
418     5
419     5
       ..
501     1
502     1
504     1
505     1
1273    1
Name: count, Length: 896, dtype: int64

In [5]:
df.idx_new.value_counts()

idx_new
8      15
103    14
151    14
36     13
158    13
       ..
123     1
43      1
141     1
94      1
381     1
Name: count, Length: 688, dtype: int64

In [2]:
df.sort_values("max_stops", ascending=True)

,segment,total_duration,stops_airports,max_stops,max_stop_duration,carriers,segment_durations,segments_time,segments_airports,segments_rating,tags,is_mixed,idx,currency,price,url,flights_baggage,flights_handbags,flight_additional_tariff_infos,viable_handbags,viable_baggage,has_handbags,has_baggage,flight_to,flight_back,tariff_to,tariff_back,rounded_price_5k,has_exchange,has_return,airlines_list_to,airlines_list_back,flight_to_time_raw,flight_back_time_raw,flight_to_time,flight_back_time,has_blacklisted_airlines,has_preferred_airlines
0,[{'flight': [{'aircraft': 'Airbus A321-100/200...,710,"['SAW', 'FCO']",1,310,['PC'],[710],"[[1750992900, 1751031900]]","[['LED', 'FCO']]",6.574,"['convenient_ticket', 'long_layover']",NaN,0,rub,52435,3600000,"[['1PC20', '1PC20']]","[['1PC3x30x15x40', '1PC3x30x15x40']]",[[{'return_before_flight': {'available': False...,1PC3x30x15x40,1PC20,True,True,{'flight': [{'aircraft': 'Airbus A321-100/200'...,{},[{'return_before_flight': {'available': False}...,NaN,50000,False,False,"['PC', 'PC']",[],02:55,0,2,0,False,True
783,[{'flight': [{'aircraft': 'Airbus A321-100/200...,1290,"['SAW', 'FCO']",1,880,"['PC', 'VF']",[1290],"[[1751036400, 1751110200]]","[['LED', 'FCO']]",5.726,"['has_night_transfer', 'night_transfer', 'over...",NaN,782,rub,58506,18300362,"[['1PC20', '1PC20']]","[['1PC8', '1PC8x40x23x55']]",[[{'return_before_flight': {'available': True}...,1PC8,1PC20,True,True,{'flight': [{'aircraft': 'Airbus A321-100/200'...,{},"[{'return_before_flight': {'available': True},...",NaN,60000,True,False,"['PC', 'VF']",[],15:00,0,15,0,False,True
724,[{'flight': [{'aircraft': 'Airbus A321-100/200...,985,"['SAW', 'FCO']",1,590,"['PC', 'TK']",[985],"[[1750992900, 1751048400]]","[['LED', 'FCO']]",5.909,"['long_layover', 'airport_change']",NaN,751,rub,54300,18300278,"[['1PC20', '1PC23']]","[['1PC8', '1PC8x40x23x55']]",[[{'return_before_flight': {'available': False...,1PC8,1PC20,True,True,{'flight': [{'aircraft': 'Airbus A321-100/200'...,{},[{'return_before_flight': {'available': False}...,NaN,50000,True,False,"['PC', 'TK']",[],02:55,0,2,0,False,True
723,[{'flight': [{'aircraft': 'Airbus A321-100/200...,985,"['SAW', 'FCO']",1,590,"['PC', 'TK']",[985],"[[1750992900, 1751048400]]","[['LED', 'FCO']]",5.909,"['long_layover', 'airport_change']",NaN,751,rub,54300,18300277,"[['1PC20', '1PC23']]","[['1PC8', '1PC8x40x23x55']]",[[{'return_before_flight': {'available': False...,1PC8,1PC20,True,True,{'flight': [{'aircraft': 'Airbus A321-100/200'...,{},[{'return_before_flight': {'available': False}...,NaN,50000,False,False,"['PC', 'TK']",[],02:55,0,2,0,False,True
722,[{'flight': [{'aircraft': 'Airbus A321-100/200...,575,"['SAW', 'FCO']",1,165,"['VF', 'PC']",[575],"[[1750992900, 1751023800]]","[['LED', 'FCO']]",7.155,['convenient_ticket'],NaN,749,rub,54403,18300274,"[['1PC20', '1PC20']]","[['1PC8', '1PC8x40x23x55']]",[[{'return_before_flight': {'available': False...,1PC8,1PC20,True,True,{'flight': [{'aircraft': 'Airbus A321-100/200'...,{},[{'return_before_flight': {'available': False}...,NaN,50000,True,False,"['PC', 'VF']",[],02:55,0,2,0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,[{'flight': [{'aircraft': 'Sukhoi Superjet 100...,1915,"['SVO', 'EVN', 'LCA', 'FCO']",3,935,"['W4', 'FV', 'SU', 'W6']",[1915],"[[1751007600, 1751118900]]","[['LED', 'FCO']]",4.351,"['long_layover', 'has_night_transfer', 'night_...",NaN,647,rub,61314,18300046,"[['1PC23', '1PC23', '1PC20', '1PC20']]","[['1PC10x40x25x55', '1PC10x40x25x55', '1PC10x3...",[[{'return_before_flight': {'available': True}...,1PC10x30x20x40,1PC20,True,True,{'flight': [{'aircraft': 'Sukhoi Superjet 100'...,{},"[{'return_before_flight': {'available': True},...",NaN,60000,False,False,"['FV', 'SU', 'W6', 'W4']",[],07:00,0,7,0,False,True
545,[{'flight': [{'aircraft': 'Airbus A321-100/200...,3635,"['SAW', 'BEG', 'CDG', 'LUX', 'FCO']",4,1370,"['PC', 'JU', 'LG']",[3635],"[[1750992900, 1751207400]]","[['LED', 'FCO']]",3.319,"['has_night_transfer', 'night_transfer', 'airp...",NaN,557,rub,63818,14800799,"[['1PC20', '1PC23', '1PC23', '1PC23', '1PC23']]","[['1PC8', '1PC8x40x23x55', '1PC8x40x23x55', '1...",[[{'return_before_flight': {'available': False...,1PC8,1PC20,True,True,{'flight': [{'aircraft': 'Airbus A321-100/200'...,{},[{'return_before_flight': {'available': False}...,NaN,60000,True,False,"['PC', 'JU', 'JU', 'LG', 'LG']",[],02:55,0,2,0,False,True
546,[{'flight': [{'aircraft': 'Airbus A321-100/200...,3635,"['SAW', 'BEG', 'CDG', 'LUX', 'FCO']",4,1370,"['PC', 'JU', 'LG']",[3635],"[[1750992900, 1751207400]]","[['LED', 'FCO']]",3.319,"['has_night_transfer', 'night_transfer', 'airp...",NaN,557,rub,63818,14800800,"[['1PC20', '1PC23', '1PC23', '1PC23', '1PC23']]","[['1PC8', '1PC8x40x23x55', '1PC8x40x23x55', '1...",[[{'return_before_flight': {'available': False...,1PC8,1PC20,True,True,{'flight': [{'aircraft': 'Airbus A321-100/200'...,{},[{'return_before_flight': {'available': False}...,NaN,60000,False,False,"['PC', 'JU', 'JU', 'LG', 'LG']",[],02:55,0,2,0,False,True
543,[{'flight': [{'aircraft': 'Airbus A321-100/200...,3635,"['SAW', 'BEG', 'CDG', 'LUX', 'FCO']",4,895,"['PC', 'JU', 'LG']",[3635],"[[1750992900, 1751207400]]","[['LED', 'FCO']]",3.319,"['long_layover', 'has_night_transfer', 'night_...",NaN,556,rub,63818,14800797,"[['1PC20', '1PC23', '1PC23', '1PC23', '1PC23']]","[['1PC8', '1PC8x40x23x55', '1PC8x40x23x55', '1...",[[{'return_before_flight': {'available': False...,1PC8,1PC20,True,True,{'flight': [{'aircraft': 'Airbus A321-100/200'...,{},[{'return_before_flight': {'available': False}...,NaN,60000,True,False,"['PC', 'JU', 'JU', 'LG', 'LG']",[],02:55,0,2,0,False,True
544,[{'flight': [{'aircraft': 'Airbus A321-100/200...,3635,"['SAW', 'BEG', 'CDG', 'LUX', 'FCO']",4,895,"['PC', 'JU', 'LG']",[3635],"[[1750992900, 1751207400]]","[['LED', 'FCO']]",3.319,"['long_layover', 'has_night_transfer', 'night_...",NaN,556,rub,63818,14800798,"[['1PC20', '1PC23', '1PC23', '1PC23', '1PC23']]","[['1PC8', '1PC8x40x23x55', '1PC8x40x23x55', '1...",[[{'return_before_flight': {'available': False...,1PC8,1PC20,True,True,{'flight': [{'aircraft': 'Airbus A321-100/200'...,{},[{'return_before_flight': {'available': False}...,NaN,60000,False,False,"['PC', 'JU', 'JU', 'LG', 'LG']",[],02:55,0,2,0,False,True

In [25]:
eval(df.iloc[1].segment)

[{'flight': [{'aircraft': 'Sukhoi Superjet 100',
    'arrival': 'SVO',
    'arrival_date': '2025-06-27',
    'arrival_time': '13:00',
    'arrival_timestamp': 1751018400,
    'delay': 0,
    'departure': 'LED',
    'departure_date': '2025-06-27',
    'departure_time': '11:30',
    'departure_timestamp': 1751013000,
    'duration': 90,
    'equipment': 'SU9',
    'local_arrival_timestamp': 1751029200,
    'local_departure_timestamp': 1751023800,
    'marketing_carrier': 'SU',
    'number': '6168',
    'operating_carrier': 'FV',
    'operated_by': 'FV',
    'rating': 0,
    'technical_stops': None,
    'trip_class': 'Y'},
   {'aircraft': 'Boeing 737-800 (winglets)',
    'arrival': 'EVN',
    'arrival_date': '2025-06-27',
    'arrival_time': '19:10',
    'arrival_timestamp': 1751037000,
    'delay': 100,
    'departure': 'SVO',
    'departure_date': '2025-06-27',
    'departure_time': '14:40',
    'departure_timestamp': 1751024400,
    'duration': 210,
    'equipment': '73H',
    'local_arrival_timestamp': 1751051400,
    'local_departure_timestamp': 1751035200,
    'marketing_carrier': 'SU',
    'number': '1862',
    'operating_carrier': 'SU',
    'operated_by': 'SU',
    'rating': 0,
    'technical_stops': None,
    'trip_class': 'Y'},
   {'aircraft': 'Airbus A321neo',
    'arrival': 'FCO',
    'arrival_date': '2025-06-28',
    'arrival_time': '15:10',
    'arrival_timestamp': 1751116200,
    'delay': 1065,
    'departure': 'EVN',
    'departure_date': '2025-06-28',
    'departure_time': '12:55',
    'departure_timestamp': 1751100900,
    'duration': 255,
    'equipment': '32Q',
    'local_arrival_timestamp': 1751123400,
    'local_departure_timestamp': 1751115300,
    'marketing_carrier': 'W4',
    'number': '6168',
    'operating_carrier': 'W4',
    'operated_by': 'W4',
    'rating': 0,
    'technical_stops': None,
    'trip_class': 'Y'}],
  'rating': {'total': 4.468},
  'transfers': [{'at': 'SVO',
    'to': 'SVO',
    'airports': ['SVO'],
    'airlines': ['FV', 'SU'],
    'country_code': 'RU',
    'city_code': 'MOW',
    'visa_rules': {'required': False},
    'night_transfer': False,
    'tags': [],
    'duration_seconds': 6000,
    'duration': {'seconds': 6000}},
   {'at': 'EVN',
    'to': 'EVN',
    'airports': ['EVN'],
    'airlines': ['SU', 'W4'],
    'country_code': 'AM',
    'city_code': 'EVN',
    'visa_rules': {'required': False},
    'night_transfer': True,
    'tags': ['overnight_layover'],
    'duration_seconds': 63900,
    'duration': {'seconds': 63900}}]}]